source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

#1、纯OC项目中，通过cocoapods导入OC库时，一般都不使用use_frameworks!
#2、纯swift项目中，通过cocoapods导入swift库时，必须使用use_frameworks!
#3、只要是通过cocoapods导入swift库时，都必须使用use_frameworks!
#4、使用动态链接库dynamic frameworks时，必须使用use_frameworks!
use_frameworks!
 
inhibit_all_warnings!

target "WDEMO" do
#图片
pod 'SDWebImage', '~> 5.0'
pod 'SDWebImageWebPCoder'
#刷新
pod 'MJRefresh'
#网络请求
pod 'AFNetworking','~> 3.0’
#UI布局
pod 'Masonry', '~> 1.0.1'
#RAC
pod 'ReactiveObjC', '~> 2.0'
#YYKit
pod 'YYKit', '~> 1.0'
#HUD
pod 'MBProgressHUD', '~> 1.2.0'
#无限循环控件
pod 'SDCycleScrollView'
#动画 JSON动画
pod 'lottie-ios', '~> 2.5.3'
#pod 'FLAnimatedImage', '~> 1.0'
#Aspects是一个简洁高效的用于使iOS支持AOP面向切面编程的库
#https://www.jianshu.com/p/10d342ae6ccd
pod 'AspectsV1.4.2', '~> 1.4.2’

#下载
#pod 'YCDownloadSession', '~> 2.0.2', :subspecs => ['Core', 'Mgr']

#网络
#pod 'YTKNetwork'

#空白数据集显示框架
#pod 'DZNEmptyDataSet'

#首页tabPageController
#pod 'WMPageController', '~> 2.4.0'

#一个支持多选、选原图和视频的图片选择器，同时有预览功能，支持iOS6+。
#pod 'TZImagePickerController'
#图片选择器
#pod 'HXPhotoPicker', '~> 2.2.5' 搜索不到库或最新版请执行pod repo update

#类似微博主页、简书主页、QQ联系人页面等效果。多页面嵌套，既可以上下滑动，也可以左右滑动切换页面。支持HeaderView悬浮、支持下拉刷新、上拉加载更多。
#pod 'JXPagingView/Pager'

#KVO
#pod 'KVOController'

#iOS使用UICountingLabel实现数字变化的动画效果
#pod 'UICountingLabel'
end
