platform :ios, '8.0'
inhibit_all_warnings!

target "WDEMO" do
#图片
pod 'SDWebImage', '~>3.8'
#网络请求
pod 'MJRefresh'
pod 'AFNetworking','~> 3.0’
#UI
pod 'Masonry', '~> 1.0.1'
#RAC
pod 'ReactiveObjC', '~> 2.0'

pod 'YYKit', '~> 1.0'
#HUD
pod 'MBProgressHUD', '~> 1.2.0'
#动画
pod 'lottie-ios' '~> 2.5.3'
end
